// Keys compiled into the firmware (used until something is written over BLE).
// keys/triki_keys.h (not in git) is generated by tools/make_default_keys.py.
// All zeros = no key, that network stays silent.
#ifndef DEFAULT_KEYS_H
#define DEFAULT_KEYS_H

#if __has_include("triki_keys.h")
#include "triki_keys.h"
#else
#define DEFAULT_APPLE_KEY { 0 }
#define DEFAULT_FMDN_KEY { 0 }
#define DEFAULT_APPLE_ENABLED 1
#define DEFAULT_FMDN_ENABLED 1
#endif

// Game-mode identity (advertised BLE address + name). Off by default; set it in
// keys/triki_keys.h or over BLE with tools/triki_config.py --game-mac/--game-name.
#ifndef DEFAULT_GAME_MAC
#define DEFAULT_GAME_MAC { 0 }
#endif
#ifndef DEFAULT_GAME_NAME
#define DEFAULT_GAME_NAME { 0 }
#endif
#ifndef DEFAULT_GAME_NAME_LEN
#define DEFAULT_GAME_NAME_LEN 0
#endif

#endif
