#!/usr/bin/env python3
"""Generate keys/triki_keys.h with keys compiled into the firmware (not committed).

  -k KEYFILE  OpenHaystack/macless-haystack *_keyfile (1 byte count + N x 28 byte
              public keys); only the first key is used
  -f HEX      Google FMDN EID, 20 bytes as 40 hex characters
"""
import argparse
import os

p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
p.add_argument('-k', '--keyfile')
p.add_argument('-f', '--fmdn')
p.add_argument('-o', '--out', default=os.path.join(os.path.dirname(__file__), '..', 'keys', 'triki_keys.h'))
a = p.parse_args()

apple = bytes(28)
if a.keyfile:
    data = open(a.keyfile, 'rb').read()
    if len(data) < 29 or data[0] < 1:
        raise SystemExit('keyfile has no keys')
    apple = data[1:29]
fmdn = bytes(20)
if a.fmdn:
    fmdn = bytes.fromhex(a.fmdn)
    if len(fmdn) != 20:
        raise SystemExit('FMDN key must be 20 bytes (40 hex characters)')

arr = lambda b: '{ ' + ', '.join('0x%02x' % x for x in b) + ' }'
os.makedirs(os.path.dirname(os.path.abspath(a.out)), exist_ok=True)
open(a.out, 'w').write(f'''// Generated by tools/make_default_keys.py - contains your keys, do not commit
#ifndef TRIKI_KEYS_H
#define TRIKI_KEYS_H

#define DEFAULT_APPLE_KEY {arr(apple)}
#define DEFAULT_FMDN_KEY {arr(fmdn)}
#define DEFAULT_APPLE_ENABLED 1
#define DEFAULT_FMDN_ENABLED 1

#endif
''')
print('written', os.path.normpath(a.out))
